### ISSUE TITLE
.mil links

### ISSUE THREAD

**Issue by jcozzo** [CommunicateHealth/outlink.js#4]
Hi Jason,

I just a site to treat .mil links like .gov links - what do you think about pulling that change in here?

Please let me know if there is any reason not to include .mil links that I should bring back to the team!

Thanks,
Jocelyn

**Comment by jsnmrs** [comment]
I'm on board with adding .mil here. It seems like equal treatment of .gov and .mil links is a consistent policy. I hardly ever see them, though.

Thanks for spotting this. Please add!

**Comment by jcozzo** [comment]
Ok, great! .mil handling is in - please let me know if you see anything weird!

**Comment by jsnmrs** [comment]
👍 Looks and works great - thanks!
